#!/bin/sh

currentDir=$( echo ${PWD##*/} )

if [ currentDir != 'LeadPagesBuildSystem' ]; then


	# New Template. Switch branch to yeoman to copy the skeleton folders and files
	if [ ! -d "leadpages-template" ]; then
		echo "No leadpages-template folder found. Getting a skeleton copy."

		mkdir tmp && \
		git checkout yeoman && \
		mv ./tmp/leadpages-template ../leadpages-template && \
		git co master && \
		rm install && \
		rm -rf tmp readme.md
	else
		#Existing Template without Git
		echo "Installing Build System..."
		rm ../install
	fi

	if [ ! -d ".git" ]; then
		git init && git add . LeadPagesBuildSystem && git status
	fi
else
	rm -rf .git .gitignore readme.md && \
	mv * ../
	cd ..
	rm -rf LeadPagesBuildSystem
fi

echo "Done! Happy coding!"