#!/bin/sh

if [ ! -d "../leadpages-template" ]; then
	echo "No leadpages-template folder found. Getting a skeleton copy and initializing git."

	git checkout yeoman && \
	cp -r ./leadpages-template ../leadpages-template && \
	cd .. && \
	rm -rf LeadPagesBuildSystem && \
	rm install && \
	git init && git add . LeadPagesBuildSystem && git status
else
	echo "Installing Build System..."

	cp -r * ../
	cd ..
	rm -rf LeadPagesBuildSystem && rm ../install
fi

echo "Done! Happy coding!"