#!/bin/sh

echo "Installing a clean project"

if [ ! -d "leadpages-template" ]; then
	echo "No leadpages-template folder found. Getting a skeleton copy."

	mkdir tmp && \
	git co yeoman && \
	cp -r ./leadpages-template tmp && \
	git co fork && \
	cp -r ./tmp/leadpages-template .
fi

rm -rf .git tmp && rm install && \
git init && git add . && git status

echo "Done! Happy coding!"